# Generated by Django 5.1.7 on 2025-04-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_hectres', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('suitable_crops', models.CharField(max_length=100)),
                ('estimate_of_harvest_yield', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField()),
                ('rent_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
