# Generated by Django 5.1.7 on 2025-04-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriKonnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_hectres', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('suitable_crops', models.CharField(max_length=100)),
                ('estimate_of_harvest_yield', models.CharField(max_length=100)),
                ('for_rent', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('sale_price', models.CharField(max_length=100)),
                ('rent_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='Plots',
        ),
    ]
