# Generated by Django 5.1.7 on 2025-04-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriKonnect', '0002_plot_delete_plots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='rent_price',
            field=models.CharField(max_length=100),
        ),
    ]
