# Generated by Django 5.1.7 on 2025-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriKonnect', '0003_alter_plot_for_rent_alter_plot_rent_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='size_in_hectres',
        ),
        migrations.AddField(
            model_name='plot',
            name='size_in_hectares',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
