# Generated by Django 5.1.7 on 2025-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriKonnect', '0004_remove_plot_size_in_hectres_plot_size_in_hectares'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name_of_owner',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='owner_contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
