# Generated by Django 5.1.7 on 2025-04-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriKonnect', '0005_plot_name_of_owner_plot_owner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='owner_contact',
            field=models.CharField(max_length=100),
        ),
    ]
